/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FlashLoanProviderService } from "../flashLoanProvider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FlashLoanProviderCreateInput } from "./FlashLoanProviderCreateInput";
import { FlashLoanProvider } from "./FlashLoanProvider";
import { FlashLoanProviderFindManyArgs } from "./FlashLoanProviderFindManyArgs";
import { FlashLoanProviderWhereUniqueInput } from "./FlashLoanProviderWhereUniqueInput";
import { FlashLoanProviderUpdateInput } from "./FlashLoanProviderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FlashLoanProviderControllerBase {
  constructor(
    protected readonly service: FlashLoanProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FlashLoanProvider })
  @nestAccessControl.UseRoles({
    resource: "FlashLoanProvider",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFlashLoanProvider(
    @common.Body() data: FlashLoanProviderCreateInput
  ): Promise<FlashLoanProvider> {
    return await this.service.createFlashLoanProvider({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        providerName: true,
        apiUrl: true,
        maximumLoanAmount: true,
        fees: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FlashLoanProvider] })
  @ApiNestedQuery(FlashLoanProviderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FlashLoanProvider",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flashLoanProviders(
    @common.Req() request: Request
  ): Promise<FlashLoanProvider[]> {
    const args = plainToClass(FlashLoanProviderFindManyArgs, request.query);
    return this.service.flashLoanProviders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        providerName: true,
        apiUrl: true,
        maximumLoanAmount: true,
        fees: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FlashLoanProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FlashLoanProvider",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async flashLoanProvider(
    @common.Param() params: FlashLoanProviderWhereUniqueInput
  ): Promise<FlashLoanProvider | null> {
    const result = await this.service.flashLoanProvider({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isActive: true,
        providerName: true,
        apiUrl: true,
        maximumLoanAmount: true,
        fees: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FlashLoanProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FlashLoanProvider",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFlashLoanProvider(
    @common.Param() params: FlashLoanProviderWhereUniqueInput,
    @common.Body() data: FlashLoanProviderUpdateInput
  ): Promise<FlashLoanProvider | null> {
    try {
      return await this.service.updateFlashLoanProvider({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isActive: true,
          providerName: true,
          apiUrl: true,
          maximumLoanAmount: true,
          fees: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FlashLoanProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FlashLoanProvider",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFlashLoanProvider(
    @common.Param() params: FlashLoanProviderWhereUniqueInput
  ): Promise<FlashLoanProvider | null> {
    try {
      return await this.service.deleteFlashLoanProvider({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isActive: true,
          providerName: true,
          apiUrl: true,
          maximumLoanAmount: true,
          fees: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
